# on:
#   push:
#     branches:
#       - dev-portal
# jobs:
  
#   deploy_to_dev_stand:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Deploy via SSH
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.DEV_STAND_SSH_HOST }}
#           username: ${{ secrets.DEV_STAND_SSH_USERNAME }}
#           key: ${{ secrets.DEV_STAND_SSH_PRIVATE_KEY }}
#           script: |
         
#             cd ${{secret}}

#             docker compose down
            
#             # docker compose down -v

#             git pull origin dev-portal --force

#             docker compose up --build -d